-- MySQL Script generated by MySQL Workbench
-- Wed Mar 15 05:22:24 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema plena
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema plena
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `plena` DEFAULT CHARACTER SET utf8 ;
USE `plena` ;

-- -----------------------------------------------------
-- Table `plena`.`equipamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plena`.`equipamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `setor` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plena`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plena`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` CHAR(128) NOT NULL,
  `salt` CHAR(128) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plena`.`registros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plena`.`registros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_servico` VARCHAR(45) NOT NULL,
  `descricao_tipo_servico` LONGTEXT NOT NULL,
  `descricao_servico` VARCHAR(45) NOT NULL,
  `data_inicio` VARCHAR(45) NOT NULL,
  `hora_inicio` VARCHAR(45) NOT NULL,
  `data_termino` VARCHAR(45) NOT NULL,
  `hora_termino` VARCHAR(45) NOT NULL,
  `soma_tempo` VARCHAR(45) NOT NULL,
  `parada` VARCHAR(45) NOT NULL,
  `causas` VARCHAR(45) NULL,
  `horas_parada` VARCHAR(45) NULL,
  `data` DATETIME(45) NOT NULL,
  `equipamento_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_registros_equipamentos1_idx` (`equipamento_id` ASC),
  INDEX `fk_registros_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_registros_equipamentos1`
    FOREIGN KEY (`equipamento_id`)
    REFERENCES `plena`.`equipamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registros_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `plena`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plena`.`mecanicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plena`.`mecanicos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `inscricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plena`.`pecas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plena`.`pecas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `quantidade` INT NOT NULL,
  `registros_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pecas_registros_idx` (`registros_id` ASC),
  CONSTRAINT `fk_pecas_registros`
    FOREIGN KEY (`registros_id`)
    REFERENCES `plena`.`registros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plena`.`operantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plena`.`operantes` (
  `mecanicos_id` INT NOT NULL,
  `registros_id` INT NOT NULL,
  PRIMARY KEY (`mecanicos_id`, `registros_id`),
  INDEX `fk_mecanicos_has_registros_registros1_idx` (`registros_id` ASC),
  INDEX `fk_mecanicos_has_registros_mecanicos1_idx` (`mecanicos_id` ASC),
  CONSTRAINT `fk_mecanicos_has_registros_mecanicos1`
    FOREIGN KEY (`mecanicos_id`)
    REFERENCES `plena`.`mecanicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mecanicos_has_registros_registros1`
    FOREIGN KEY (`registros_id`)
    REFERENCES `plena`.`registros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plena`.`login_attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plena`.`login_attempts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `IP` VARCHAR(20) NOT NULL,
  `time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_login_attempts_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_login_attempts_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `plena`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
