<script type="text/javascript">
    jQuery(document).ready(function($) {
        $("#senhac").keyup(function(event) {
            if($(this).val() == $("#senha").val()){
                $(this).css({
                    border: '1px solid green'
                });
                $(".btn").attr("disabled",false);
            }
        });
        $("#senhac").blur(function(event) {
            if($(this).val() == $("#senha").val()){
                $(this).css({
                    border: '1px solid green'
                });
                $(".btn").attr("disabled",false);
            }
        });
    });
</script>
<section id="index-container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2" id="index-wrapper">
            <div class="panel panel-primary animated flipInY">
                <div class="panel-heading">
                    <h3 class="panel-title text-center">     
                        CADASTRO USUÁRIO
                    </h3>      
                </div>
                <div class="panel-body">
                    <form method="POST" action="<?=SITE?>login/salvar">
                        <div class="form-group">
                            <label for="nome">Nome Completo</label>
                            <input type="text" class="form-control" required="" name="nome" id="nome" placeholder="Nome Completo">
                        </div>
                        <div class="form-group">
                            <label for="matricula">Matricula</label>
                            <input type="text" class="form-control" required="" name="matricula" id="matricula" placeholder="Matricula">
                        </div>
                        <div class="form-group">
                            <label for="senha">Senha</label>
                            <input type="password" class="form-control" required="" name="senha" id="senha" placeholder="Senha">
                        </div>
                        <div class="form-group">
                            <label for="senhac">Confime a Senha</label>
                            <input type="password" class="form-control" required="" name="senhac" id="senhac" placeholder="Senha">
                        </div>
                        <button type="submit" disabled="" class="btn btn-success">Cadastrar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

</section>
