<section id="index-container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2" id="index-wrapper">
			<div class="panel panel-primary animated flipInY">
				<div class="panel-heading">
					<h3 class="panel-title text-center">     
						CADASTRO DE EQUIPAMENTO
					</h3>      
				</div>
				<div class="panel-body">
					<form method="post" action="<?=SITE?>equipamento/salvar" enctype="multipart/form-data">
						<div class="form-group">
							<label for="tag">TAG</label>
							<input type="text" class="form-control" required="" id="tag" placeholder="TAG" name="tag">
						</div>
						<div class="form-group">
							<label for="desEquip">Descrição do equipamento</label>
							<textarea class="form-control" id="desEquip" required="" name="desEquip" rows="3" placeholder="Descrição do Equipamento"></textarea>
						</div>
						<button class="btn btn-success btn-lg"><b>Cadastrar</b></button>
					</form>
				</div>
			</div>
		</div>
	</div>
</section>