<section id="index-container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2" id="index-wrapper">
			<div class="panel panel-primary animated flipInY">
				<div class="panel-heading">
					<h3 class="panel-title text-center">     
						Cadastro de mecanico
					</h3>      
				</div>
				<div class="panel-body">
					<form method="post" action="<?=SITE?>mecanico/salvarM" enctype="multipart/form-data">
						<div class="form-group">
						<label for="inscricao">Incrição</label>
							<input type="number" class="form-control" required="" id="inscricao" placeholder="Inscricao" name="inscricao">
						</div>
						<div class="form-group">
							<label for="nome">Nome completo</label>
							<input type="text" class="form-control" required="" id="nome" placeholder="Nome Completo" name="nome">
						</div>
						<button class="btn btn-success btn-lg">Salvar</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</section>