   <section id="login-container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4" id="login-wrapper">
                <div class="panel panel-primary animated flipInY">
                    <div class="panel-heading">
                        <h3 class="panel-title">     
                          REDEFINIÇÃO DE SENHA
                        </h3>      
                    </div>
                    <div class="panel-body">
                       <p> Informe seu usuário para redefinir sua senha.</p>
                        <form method="post" class="form-horizontal" action="<?=SITE;?>esqueci-a-senha/enviar/" role="form">
                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="text" required="required" class="form-control" id="username" name="username" placeholder="Usuário">
                                </div>
                            </div>
                            <div class="form-group">
                               <div class="col-md-12">
                               		<button type="submit" class="btn btn-primary btn-block">Redefinir</button>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-9 pull-right">
                                    <a href="<?=SITE.'login/';?>" class="btn btn-default btn-block">Lembrou-se? Clique para logar</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </section>
