				</div>
			</div>
		</div>
		<footer class="footer text-center"> HXPHP v<?=VERSION;?> <?=date("Y");?> &copy; - Todos os direitos reservados </footer>
	</div>
	<script src="<?=SITE?>public/plugins/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="<?=SITE?>publicbootstrap/dist/js/bootstrap.min.js"></script>
    <!-- Menu Plugin JavaScript -->
    <script src="<?=SITE?>publicplugins/bower_components/sidebar-nav/dist/sidebar-nav.min.js"></script>
    <!--slimscroll JavaScript -->
    <script src="<?=JS?>jquery.slimscroll.js"></script>
    <!--Wave Effects -->
    <script src="<?=JS?>waves.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="<?=JS?>custom.min.js"></script>
</body>
</html>