<!doctype html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<meta name="author" content="Bruno C. Santos">
	<meta name="generator" content="HXPHP Framework v1.0">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?=$view_title;?></title>
	<link rel="shortcut icon" href="<?=IMG;?>favicon.ico" type="image/x-icon">
	<?=$add_css;?>
	<link rel="stylesheet" href="<?=CSS;?>bootstrap.min.css" type="text/css">
	<link rel="stylesheet" href="<?=CSS;?>font-awesome.min.css" type="text/css">
	<link href="<?=CSS;?>/animate.css" rel="stylesheet">
	<link href="<?=CSS?>/style.css" rel="stylesheet">
	<link href="<?=CSS?>/colors/default.css" id="theme" rel="stylesheet">
	<link href="<?=SITE?>public/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.css" rel="stylesheet">
	<link rel="stylesheet" href="<?=CSS;?>style.css" type="text/css">
	<script type="text/javascript" src="<?=JS;?>jquery.min.js"></script>
	<script type="text/javascript" src="<?=JS;?>bootstrap.min.js"></script>
	<?=$add_js;?>
	<script type="text/javascript" src="<?=JS;?>main.js"></script>
</head>
<body class="fix-header">
	<div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
        </svg>
    </div>
    <!-- ============================================================== -->
    <!-- Wrapper -->
    <!-- ============================================================== -->
    <div id="wrapper">
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <nav class="navbar navbar-default navbar-static-top m-b-0">
            <div class="navbar-header">
                <div class="top-left-part">
                    <!-- Logo -->
                    <a class="logo" href="index.html">
                        <!-- Logo icon image, you can use font-icon also --><b>
                        <!--This is dark logo icon--><img src="<?=IMG;?>hxphp-logo.png" alt="home" class="dark-logo" /><!--This is light logo icon--><img src="<?=IMG;?>hxphp-logo.png" alt="home" class="light-logo" />
                    </b>
                    <!-- Logo text image you can use text also --><span class="hidden-xs">
                    <!--This is dark logo text--><img src="<?=IMG;?>hxphp-logo.png" alt="home" class="dark-logo" /><!--This is light logo text--><img src="<?=IMG;?>hxphp-logo.png" alt="home" class="light-logo" />
                </span> </a>
            </div>
            <!-- /Logo -->
            <ul class="nav navbar-top-links navbar-right pull-right">
                    <li class="dropdown">
					      <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <?=$view_user->full_name;?> <b class="caret"></b></a>
					      <ul class="dropdown-menu">
					        <li><a href="<?=SITE;?>usuarios/editar/<?=$view_user->id;?>">Editar perfil</a></li>
					        <li class="divider"></li>
					        <li><a href="<?=SITE;?>login/sair/">Sair</a></li>
					      </ul>
					    </li>
                </ul>
            </div>
            <!-- /.navbar-header -->
            <!-- /.navbar-top-links -->
            <!-- /.navbar-static-side -->
        </nav>
		<div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav slimscrollsidebar">
                <div class="sidebar-head">
                    <h3><span class="fa-fw open-close"><i class="ti-close ti-menu"></i></span> <span class="hide-menu">Navigation</span></h3>
                </div>
                <ul class="nav" id="side-menu">
                <li>
                    <a href="<?=SITE?>home" class="waves-effect"><i class="fa fa-user fa-fw" aria-hidden="true"></i>Profile</a>
                </li>
				<?=$view_menu;?>
				</ul>
			</div>
		</div>


	
<div id="page-wrapper">
<?=$view_message;?>
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">