<!doctype html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<meta name="author" content="Bruno C. Santos">
	<meta name="generator" content="HXPHP Framework v1.0">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?=$view_title;?></title>
	<link rel="shortcut icon" href="<?=IMG;?>favicon.ico" type="image/x-icon">
	<?=$add_css;?>
	<link rel="stylesheet" href="<?=CSS;?>bootstrap.min.css" type="text/css">
	<link rel="stylesheet" href="<?=CSS;?>font-awesome.min.css" type="text/css">
	<link rel="stylesheet" href="<?=CSS;?>style.css" type="text/css">
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script type="text/javascript" src="<?=JS;?>bootstrap.min.js"></script>
	<?=$add_js;?>
	<script type="text/javascript" src="<?=JS;?>main.js"></script>
</head>
<body>
	<div class="full bg" id="header">
		<div class="container">
			<div class="col-md-12">
				<a href="<?=SITE;?>" class="logo col-md-offset-4 col-md-4">
					<div class="col-md-10 col-md-offset-1">
						<img class="img-responsive" src="<?=IMG;?>hxphp-logo.png" alt="">
					</div>
				</a>
			</div>
		</div>
	</div>
	<style type="text/css">
		.footer{
			left: 0px;
		}
	</style>
	<?=$view_message;?>

	<div class="container-fluid">
			<div class="col-md-12">