   <section id="index-container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2" id="index-wrapper">
                <div class="panel panel-primary animated flipInY">
                    <div class="panel-heading">
                        <h3 class="panel-title text-center">     
                            SEJA BEM VINDO
                        </h3>      
                    </div>
                    <div class="panel-body">
                        <iframe width="100%" height="400" src="https://www.youtube.com/embed/SWCpldFrDfI" frameborder="0" allowfullscreen></iframe>
                    </div>
                </div>
            </div>
        </div>

    </section>
