   <section id="login-container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4" id="login-wrapper">
                <div class="panel panel-primary animated flipInY">
                    <div class="panel-heading">
                        <h3 class="panel-title text-center">     
                           ACESSO
                        </h3>      
                    </div>
                    <div class="panel-body">
                       <p> Informe suas credenciais para acessar o administrativo.</p>
                        <form method="post" class="form-horizontal" action="<?=SITE;?>login/logar/" role="form">
                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="text" value="<?=$view_user?>" required="required" class="form-control" id="username" name="username" placeholder="Usuário">
                                </div>
                            </div>
                            <div class="form-group">
                               <div class="col-md-12">
                                    <input type="password" required="required" class="form-control" id="password" name="password" placeholder="Senha">
                                </div>
                            </div>
                            <div class="form-group">
                               <div class="col-md-12">
                               		<button type="submit" class="btn btn-primary btn-block">Entrar</button>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-6 pull-right">
                                    <a href="<?=SITE.'login/cadastro';?>" class="btn btn-default btn-block">Cadastre-se</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </section>
