   <section id="index-container">
   	<div class="row">
   		<div class="col-md-8 col-md-offset-2" id="index-wrapper">
   			<div class="panel panel-primary animated flipInY">
   				<div class="panel-heading">
   					<h3 class="panel-title text-center">     
   						CADASTRAR SETOR
   					</h3>      
   				</div>
   				<div class="panel-body">
   				<form method="post" action="<?=SITE?>setor/cadastrar" enctype="multipart/form-data">
   						<div class="form-group">
   							<label for="inscricao">Nome do Setor</label>
   							<input type="text" class="form-control" required="" id="nome" placeholder="Nome do Setor" name="nome">
   						</div>
   						<a href="<?=SITE?>setor" class="btn btn-danger btn-lg">Voltar</a>
   						<button class="btn btn-success btn-lg">Cadastrar</button>
   					</form>
   				</div>
   			</div>
   		</div>
   	</div>

   </section>
