   <section id="index-container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2" id="index-wrapper">
                <div class="panel panel-primary animated flipInY">
                    <div class="panel-heading">
                        <h3 class="panel-title text-center">     
                            Setores
                        </h3>      
                    </div>
                    <div class="panel-body">
                        <table class="table table-borded">
                            <thead>
                                <th>Nome</th>
                                <th></th>
                            </thead>
                            <tbody>
                                <?php foreach($view_setores as $val){ ?>
                                    <tr>
                                        <th><?=$val->nome?></th>
                                        <td><a href="<?=SITE?>Setor/alterar/<?=$val->id?>" class='btn btn-warning'>Editar</a><a href="<?=SITE?>Setor/deletar/<?=$val->id?>" class='btn btn-danger'>Excluir</a></td>
                                    </tr>
                                <?php } ?>  
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </section>
