   <script type="text/javascript">
      $(document).ready(function() {
         $("select").blur(function(event) {
            $("select").find('option').each(function(index, el) {
               if($(this).attr("value") == $("select").val()){
                  $("#nome").val($(this).html());   
               }
            });
         });
      });
   </script>
   <section id="index-container">
      <div class="row">
         <div class="col-md-8 col-md-offset-2" id="index-wrapper">
            <div class="panel panel-primary animated flipInY">
               <div class="panel-heading">
                  <h3 class="panel-title text-center">     
                     DELETAR SETOR
                  </h3>      
               </div>
               <div class="panel-body">
                  <form method="post" action="<?=SITE?>setor/deletar" enctype="multipart/form-data">
                     <div class="form-group">
                        <label for="">Setor</label>
                        <select name="id" class="form-control">
                           <option selected="" disabled="">Selecione...</option>
                           <?php foreach($view_setores as $val){ ?>
                           <option value="<?=$val->id?>"><?=$val->nome?></option>
                           <?php } ?>
                        </select>
                     </div>
                     <a href="<?=SITE?>setor" class="btn btn-danger btn-lg">Voltar</a>
                     <button class="btn btn-success btn-lg">DELETAR</button>
                  </form>
               </div>
            </div>
         </div>
      </div>

   </section>
