<?php 
$dias = $view_registro->soma_dias >0?$view_registro->soma_dias." Dias e ":"";$n="";
//var_dump(($view_registro->terceiros[0]));
if(isset($view_registro->terceiros[0])){
$terceiro = '<div class="well">
		<h4>Serviço de terceiros: '.$view_registro->terceiros[0]->empresa.'</h4>
		<h4>Descrição do serviço: '.$view_registro->terceiros[0]->descricao.'</h4>
		<h4>Valor do serviço: R$ '.$view_registro->terceiros[0]->valor.'</h4>
		</div>';
}else{
	$terceiro ='';
}
?>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.3/jspdf.debug.js"></script>
<script type="text/javascript">
	$(document).ready(function() {
		var doc = new jsPDF();
		var specialElementHandlers = {
			'#editor': function (element, renderer) {
				return true;
			}
		};

		$('#btGerarPDF').click(function () {
			doc.fromHTML($('#pdf').html(), 15, 15, {
				'width': 170,
				'elementHandlers': specialElementHandlers
			});
			doc.save('<?=$view_equipamento->tag."-".$view_registro->id?>.pdf');
		});
	});
</script>
<style type="text/css">
	small{
		float: right;
		margin-top: -45px;
		font-size: 10pt;
	}
	h3{
		margin: 0px;
	}
	.list-group>a>span{
		float: right;
	}
</style>

<div class="col-md-3">
	<div class= "list-group" > 
		<a href="#" class="list-group-item active"> Visualizar Registro <span class="glyphicon glyphicon-search" aria-hidden= "true" ></span></a> 
		<a href="#" class="list-group-item"  id="btGerarPDF"> Salvar Aquivo <span class="glyphicon glyphicon-download-alt" aria-hidden= "true" ></span></a> 
		<a href="#" class="list-group-item" data-toggle="modal" data-target="#myModal"> Excluir <span class="glyphicon glyphicon-floppy-remove" aria-hidden= "true" ></span></a> 
		<a href="<?=SITE.'home'?>" class="list-group-item"> Voltar <span class="glyphicon glyphicon-arrow-left" aria-hidden= "true" ></span></a>
	</div>
</div>
<div class="col-md-9 well">
	<fieldset>
		<legend><span class="label label-danger"><?=$view_registro->parada?></span><br>Manutenção <?=$view_registro->tipo_servico?><br><small>Registro: <?=$view_registro->data->format('Y/m/d H:i:s')?></small></legend>
		<h4>Equipamento: <?=$view_equipamento->tag?></h4>
		<!--<p><?=$view_equipamento->descricao?></p>-->
		<h4>Serviço realizado: <?=$view_registro->descricao_servico?></h4>
		<?=$terceiro?>
		<p>Ocorrência dia: <?=explode('-',$view_registro->data_inicio)[2]?>/<?=explode('-',$view_registro->data_inicio)[1]?>/<?=explode('-',$view_registro->data_inicio)[0]?> as <?=$view_registro->hora_inicio?><br>Inicio da manutenção: <?=explode('-',$view_registro->conserto_inicio)[2]?>/<?=explode('-',$view_registro->conserto_inicio)[1]?>/<?=explode('-',$view_registro->conserto_inicio)[0]?> as <?=$view_registro->hora_inicio_conserto?>
		  <br>Fim: <?=explode('-',$view_registro->data_termino)[2]?>/<?=explode('-',$view_registro->data_termino)[1]?>/<?=explode('-',$view_registro->data_termino)[0]?> as <?=$view_registro->hora_termino?></p>
		<p>Seviço demorou <?=$dias?><?=$view_registro->soma_horas." Horas."?></p>
		<div class="col-md-4 col-md-offset-1 well well-sm">
			<h4>Pecas utilizadas:</h4>
			<p><?php foreach($view_pecas as $val){ echo $val->quantidade." ".$val->peca.", ";}?></p>
		</div>
		<div class="col-md-4 col-md-offset-1 well well-sm">
			<h4>Operantes:</h4>
			<p><?php foreach($view_operantes as $val){ echo $val->mecanico->nome.", ";}?></p>
		</div>
	</fieldset>
</div>
<fieldset id="pdf" style="font-family: inherit;display: none">
		<legend style="display: block;
    width: 100%;
    padding: 0;
    margin-bottom: 20px;
    font-size: 21px;
    line-height: inherit;
    color: #333;
    border: 0;
    border-bottom: 1px solid #e5e5e5;"><small style="right: 0px;margin-top: -45px;font-size: 10pt;">Registro: <?=$view_registro->data->format('Y/m/d H:i:s')?></small><br><span><?=$view_registro->parada?></span><br>Manutenção: <?=$view_registro->tipo_servico?><br></legend><hr>
		<h4>Equipamento: <?=$view_equipamento->tag?></h4>
		<!--<p><?=$view_equipamento->descricao?></p>-->
		<h4>Serviço realizado:</h4><p><?=$view_registro->descricao_servico?>a</p>
		<?=$terceiro?>
		<p>Ocorrência dia: <?=explode('-',$view_registro->data_inicio)[2]?>/<?=explode('-',$view_registro->data_inicio)[1]?>/<?=explode('-',$view_registro->data_inicio)[0]?> as <?=$view_registro->hora_inicio?><br>Inicio da manutenção: <?=explode('-',$view_registro->conserto_inicio)[2]?>/<?=explode('-',$view_registro->conserto_inicio)[1]?>/<?=explode('-',$view_registro->conserto_inicio)[0]?> as <?=$view_registro->hora_inicio_conserto?>
		  <br>Fim: <?=explode('-',$view_registro->data_termino)[2]?>/<?=explode('-',$view_registro->data_termino)[1]?>/<?=explode('-',$view_registro->data_termino)[0]?> as <?=$view_registro->hora_termino?></p>
		<p>Seviço demorou <?=$dias?><?=$view_registro->soma_horas." Horas."?></p>
		<div>
			<h4>Pecas utilizadas:</h4>
			<p><?php foreach($view_pecas as $val){ echo $val->quantidade." ".$val->peca.", ";}?></p>
		</div>
		<div>
			<h4>Operantes:</h4>
			<p><?php foreach($view_operantes as $val){ echo $val->mecanico->nome.", ";}?></p>
		</div>
	</fieldset>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Confirmar a exclusão do registro?</h4>
      </div>
      <div class="modal-body">
        <p><b>Descrição do serviço:</b> <?=$view_registro->descricao_servico?></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="button" class="btn btn-danger" onclick="location='<?=SITE.'registro/excluir/'.$view_registro->id?>'">Confirmar</button>
      </div>
    </div>
  </div>
</div>